---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myvrs
spec:
  hosts:
    - my-svc
  http:
  - route:
    - destination:
        host: mydst
        subset: ss1
      weight: 20
    - destination:
        host: mydst
        subset: ss2
      weight: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mydst
spec:
  host: my-svc
  subsets:
  - name: ss1
    labels:
      version: v1
  - name: ss2
    labels:
      version: v2
